/* ══════════════════════════════════════════════════════════════════
   DER ÜBUNGSKATALOG — alle gültigen Kennungen

   Erzeugt aus der App und der Übungsbank. Zwei Aufgaben:
     1. Die Anmeldeseite prüft damit, ob eine Übung aus dem Plan
        bekannt ist — ohne die ganze App laden zu müssen.
     2. Aus dieser Liste entsteht der Abschnitt im KI-Prompt, der
        vorgibt, welche Übungen überhaupt gewählt werden dürfen.

   Nicht von Hand pflegen: neue Übungen gehören in uebungsbank.js,
   danach  node katalog-bauen.mjs  aufrufen.
   ══════════════════════════════════════════════════════════════════ */

window.FLOW_KATALOG = {
  'ab-rollout': "Ab Rollout",
  'advanced-tuck-planche': "Advanced Tuck Planche",
  'archer-klimmzuege': "Archer Pull-ups",
  'archer-liegestuetze': "Archer Push-ups",
  'atemarbeit': "Atemarbeit",
  'ausfallschritte': "Ausfallschritte",
  'australian-pullups': "Australian Pull-ups",
  'backlever-tuck': "Back Lever in der Hocke",
  'bank-dips': "Bank-Dips",
  'beinheben-haengend': "Hängendes Beinheben",
  'bird-dog': "Bird Dog",
  'bizeps-curls-ringe': "Bizeps-Curls an Ringen",
  'breite-klimmzuege': "Breite Klimmzüge",
  'breite-liegestuetze': "Breite Liegestütze",
  'brustwirbel-mobilitaet': "Brustwirbelsäulen-Mobilität",
  'bulgarian-split': "Bulgarian Split Squats",
  'chinups': "Chin-ups (Untergriff)",
  'cossack-squat': "Cossack Squat",
  'crow-pose': "Krähe",
  'dead-bug': "Dead Bug",
  'deadhang-di': "deadhang-di",
  'deficit-liegestuetze': "Liegestütze mit Tiefgang",
  'diamond-fr': "diamond-fr",
  'diamond-mo': "diamond-mo",
  'dips-barren': "Dips am Barren",
  'dragon-flag': "Dragon Flag Progression",
  'einarm-klimmzug-prog': "Einarmige Klimmzug-Progression",
  'einarm-liegestuetz': "Einarmiger Liegestütz",
  'einbeiniges-kreuzheben': "Einbeiniges Kreuzheben",
  'erhoehte-liegestuetze': "Erhöhte Liegestütze",
  'erhoehte-pike-pushups': "Erhöhte Pike Push-ups",
  'explosive-liegestuetze': "Explosive Liegestütze",
  'face-pulls-band': "Face Pulls mit Band",
  'frontlever-advanced-tuck': "Front Lever — offene Hocke",
  'frontlever-einbeinig': "Front Lever einbeinig",
  'frontlever-tuck-di': "frontlever-tuck-di",
  'frontlever-tuck-do': "frontlever-tuck-do",
  'frontlever-voll': "Front Lever gestreckt",
  'german-hang': "German Hang",
  'gew-dips': "Gewichtete Dips",
  'gew-klimmzuege': "Gewichtete Klimmzüge",
  'gew-liegestuetze': "Gewichtete Liegestütze",
  'glute-bridge': "Glute Bridge",
  'handgelenk-vorbereitung': "Handgelenk-Vorbereitung",
  'handstand-frei': "Freier Handstand",
  'handstand-negativ': "Handstand-Liegestütz negativ",
  'handstand-pushup-wand': "Handstand-Liegestütz an der Wand",
  'handstand-wand': "Handstand an der Wand",
  'handstand-wand-hold': "Handstand am Bauch zur Wand",
  'handtuch-klimmzuege': "Handtuch-Klimmzüge",
  'hang-fr': "hang-fr",
  'hangeln': "Hangeln",
  'hindu-liegestuetze': "Hindu Push-ups",
  'hollow-hold-mi': "hollow-hold-mi",
  'hollow-plank-fr': "hollow-plank-fr",
  'hollow-rock': "Hollow Rock",
  'hs-taps': "Handstand Schulter-Taps / Balance",
  'hueftbeuger-dehnung': "Hüftbeuger-Dehnung",
  'human-flag-prog': "Human Flag Progression",
  'jump-squats': "Jump Squats",
  'klimmzuege': "Klimmzüge",
  'knie-liegestuetze': "Liegestütze auf den Knien",
  'kniebeuge': "Kniebeuge",
  'l-sit': "L-Sit / Tuck L-Sit",
  'l-sit-barren': "L-Sit am Barren",
  'liegestuetze': "Liegestütze (sauber)",
  'lockeres-radfahren': "Lockeres Radfahren",
  'muscleup-bar': "Muscle-up an der Stange",
  'muscleup-drills': "Muscle-up-Drills",
  'nacken-entspannung': "Nacken lösen",
  'negative-klimmzuege': "Negative Klimmzüge",
  'nordic-curl': "Nordic Hamstring Curl",
  'pike-pushups': "Pike Push-ups",
  'pistol-progression': "Kniebeugen / Pistol-Progression",
  'planche-lean-do': "planche-lean-do",
  'planche-lean-mo': "planche-lean-mo",
  'plank': "Unterarmstütz",
  'pseudo-planche-pushups': "Pseudo-Planche Push-ups",
  'pullups-technik': "pullups-technik",
  'ring-dips': "Ring-Dips",
  'ring-muscleup': "Muscle-up an Ringen",
  'ruderzug-ringe': "Ruderzug an Ringen",
  'russian-twist': "Russian Twist",
  'scapula-pullups': "Scapula Pull-ups",
  'schulter-dislocates': "Schulterkreisen mit Stab",
  'schwimmen-locker': "Lockeres Schwimmen",
  'seitstuetz': "Seitstütz",
  'shrimp-squat': "Shrimp Squat",
  'sissy-squat': "Sissy Squat",
  'skater-jumps': "Skater Jumps",
  'skin-the-cat': "Skin the Cat",
  'split-squats': "Split Squats",
  'sprints': "Sprints / Intervalle",
  'step-ups': "Step-ups",
  'sun-mobility': "Leichte Ganzkörper-Mobilität",
  'sun-stretch': "Sanftes Dehnen",
  'sun-walk': "Spaziergang",
  'superman-hold': "Superman Hold",
  'tibialis-raises': "Tibialis Raises",
  'tiefe-hocke': "Tiefe Hocke halten",
  'toes-to-bar': "Toes to Bar",
  'tophold-klimmzug': "Top-Hold Klimmzüge",
  'towel-hang-di': "towel-hang-di",
  'trizeps-extension': "Trizeps-Strecken am Boden",
  'tuck-planche': "Tuck Planche",
  'waden-stufe': "Wadenheben an der Stufe",
  'wadenheben': "Wadenheben einbeinig",
  'wandsitzen': "Wandsitzen",
};
